# Site settings
timezone: Asia/Tokyo
title: JADH2015
email: conf2015 [ at ] jadh.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jadh2015
github_username:  jadh2015

# Build settings
markdown: kramdown
